import { AIExplanationResponse } from '../../components/common/ai/types/AIResponseTypes';
import env from '../../utils/env';
import { logError } from '../logger';

import { AIProviderType, getCurrentProviderType } from './providers/aiProvider';
import { callCurrentProvider } from './providers/AIProviderFactory';
import { AIProviderFactory, ensureApiKeyStatus } from './providers/AIProviderFactory';

export type { AIExplanationResponse };

/**
 * The four explanation sections each step renders. Splitting them into
 * separate provider calls lets the UI render each as soon as it arrives
 * instead of waiting for one large response.
 */
export type ExplanationSection = 'standard' | 'technical' | 'simplified' | 'whatIf';

/**
 * Callback invoked with a partial response each time a section resolves.
 */
export type SectionHandler = (partial: Partial<AIExplanationResponse>) => void;

const SECTION_FIELDS: Record<ExplanationSection, (keyof AIExplanationResponse)[]> = {
  standard: ['explanation'],
  technical: ['technicalDetails', 'technicalCode'],
  simplified: ['simplifiedExplanation'],
  whatIf: ['whatIfScenarios'],
};

const JSON_ONLY = 'Respond with ONLY a raw JSON object — no markdown, no code fences, no commentary.';

const SECTION_INSTRUCTIONS: Record<ExplanationSection, string> = {
  standard:
    'Provide a standard explanation that balances technical accuracy with accessibility. ' +
    `${JSON_ONLY} Shape: { "explanation": "..." }`,
  technical:
    'Provide a technical explanation with implementation details for developers, plus a code snippet ' +
    'demonstrating the implementation. ' +
    `${JSON_ONLY} Shape: { "technicalDetails": "...", "technicalCode": "..." }`,
  simplified:
    'Provide a simplified explanation for beginners with no blockchain experience. ' +
    `${JSON_ONLY} Shape: { "simplifiedExplanation": "..." }`,
  whatIf:
    'Provide 2-3 "What-if" scenarios, such as what happens if the transaction fails, the user has ' +
    'insufficient funds, or the network is congested. ' +
    `${JSON_ONLY} Shape: { "whatIfScenarios": ["Question? Answer", "Question? Answer"] }`,
};

/**
 * Derives a single-section prompt from a full explanation prompt by keeping the
 * context (everything before the multi-section instructions) and appending a
 * narrow instruction for just this section.
 * @param fullPrompt The prompt generated by a flow's generate*Prompt function
 * @param section Which explanation section to ask for
 */
export const generateSectionPrompt = (fullPrompt: string, section: ExplanationSection): string => {
  const context = fullPrompt
    .split(/Please provide three different explanations|Format your response as a JSON object/)[0]
    .trim();
  return `${context}\n\n${SECTION_INSTRUCTIONS[section]}`;
};

/**
 * Calls the current AI provider once per explanation section, in parallel.
 * Invokes onSection with each section's fields as soon as it resolves so the
 * UI can render progressively. Returns the merged response, or null if the
 * standard explanation never arrived.
 * @param fullPrompt The full prompt generated by a flow's generate*Prompt function
 * @param onSection Optional callback fired as each section resolves
 */
export const callProviderSections = async (
  fullPrompt: string,
  onSection?: SectionHandler
): Promise<AIExplanationResponse | null> => {
  const sections: ExplanationSection[] = ['standard', 'technical', 'simplified', 'whatIf'];
  const merged: AIExplanationResponse = { explanation: '' };

  await Promise.allSettled(
    sections.map(async section => {
      const partial = await callOpenAI(generateSectionPrompt(fullPrompt, section));

      const slice: Partial<AIExplanationResponse> = {};
      for (const field of SECTION_FIELDS[section]) {
        const value = partial[field];
        if (value !== undefined && value !== 'No explanation provided.') {
          (slice as Record<string, unknown>)[field] = value;
        }
      }

      Object.assign(merged, slice);
      if (Object.keys(slice).length > 0) {
        onSection?.(slice);
      }
    })
  );

  return merged.explanation ? merged : null;
};

/**
 * Calls the current AI provider with the given prompt.
 * @param prompt The text prompt to send to the AI provider for generating a response
 * @returns {Promise<AIExplanationResponse>} A promise that resolves to an explanation response from the AI provider
 * @throws Error if the API call fails or if the API key is invalid
 */
export const callOpenAI = async (prompt: string): Promise<AIExplanationResponse> => {
  await ensureApiKeyStatus();
  try {
    return await callCurrentProvider(prompt);
  } catch (error) {
    // Only log detailed error in development
    if (env.NODE_ENV === 'development') {
      logError('Error calling AI provider:', error);
    }
    throw error;
  }
};

/**
 * Tests the current AI provider's API key by making a simple request.
 * @returns {Promise<{ success: boolean; message: string }>} A promise that resolves to an object containing
 * a success flag and a descriptive message about the test result
 */
export const testOpenAIKey = async (): Promise<{ success: boolean; message: string }> => {
  await ensureApiKeyStatus();
  try {
    const factory = AIProviderFactory.getInstance();
    const providerType = getCurrentProviderType();
    if (!factory.hasValidApiKey(providerType)) {
      const envVar = {
        [AIProviderType.OPENAI]: 'OPENAI_API_KEY',
        [AIProviderType.GEMINI]: 'GEMINI_API_KEY',
        [AIProviderType.CLAUDE]: 'CLAUDE_API_KEY',
      }[providerType];
      return {
        success: false,
        message: `No API key configured. Add ${envVar} to your .env file and restart the development server.`,
      };
    }
    return await factory.getProvider().testApiKey();
  } catch (error: any) {
    if (env.NODE_ENV === 'development') {
      logError('Error testing API key:', error);
    }
    return {
      success: false,
      message: `API key test failed: ${error.message || 'Unknown error'}`,
    };
  }
};

/**
 * Generates a base prompt for the AI provider based on the flow type, step number, and step title.
 * @param flowType
 * @param stepNumber
 * @param stepTitle
 * @param defaultDescription
 * @return A formatted prompt string for the AI provider.
 */
export const generateBasePrompt = (
  flowType: string,
  stepNumber: number,
  stepTitle: string,
  defaultDescription?: string
): string => {
  // For step 0, use the defaultDescription in the prompt if provided
  if (stepNumber === 0 && defaultDescription) {
    return `
You are an expert blockchain educator. Please provide a detailed explanation for the ${flowType} flow.

Use this description as a starting point: "${defaultDescription}"

Please provide three different explanations:
1. A standard explanation that balances technical accuracy with accessibility
2. A technical explanation with implementation details for developers
3. A simplified explanation for beginners with no blockchain experience

Additionally, provide 2-3 "What-if scenarios" related to this flow. For example:
- "What happens if the transaction fails at some point?"
- "What if the user has insufficient funds?"
- "What if the network is congested during transactions?"

Format your response as a JSON object with these fields:
{
  "explanation": "Your standard explanation here",
  "technicalDetails": "Your technical explanation here",
  "technicalCode": "A code snippet that demonstrates the technical implementation of this flow",
  "simplifiedExplanation": "Your simplified explanation here",
  "whatIfScenarios": ["What-if scenario 1 with answer", "What-if scenario 2 with answer", "What-if scenario 3 with answer"]
}
`;
  }
  // for other steps, use the original prompt
  return `
You are an expert blockchain educator. Please provide a detailed explanation for step ${stepNumber} of the ${flowType} flow: "${stepTitle}".

Please provide three different explanations:
1. A standard explanation that balances technical accuracy with accessibility
2. A technical explanation with implementation details for developers
3. A simplified explanation for beginners with no blockchain experience

Additionally, provide 2-3 "What-if scenarios" related to this step. For example:
- "What happens if the transaction fails at this point?"
- "What if the user has insufficient funds?"
- "What if the network is congested during this transaction?"

Format your response as a JSON object with these fields:
{
  "explanation": "Your standard explanation here",
  "technicalDetails": "Your technical explanation here",
  "technicalCode": "A code snippet that demonstrates the technical implementation of this step",
  "simplifiedExplanation": "Your simplified explanation here",
  "whatIfScenarios": ["What-if scenario 1 with answer", "What-if scenario 2 with answer", "What-if scenario 3 with answer"]
}
`;
};
